import { isValidElement } from 'react';
import RootLayout, { metadata } from './layout';

jest.mock('next/font/local', () => ({
  __esModule: true,
  default: jest.fn(({ src }: { src: string }) => ({
    variable: src.includes('Mono') ? 'font-mono' : 'font-sans',
  })),
}));

describe('RootLayout', () => {
  it('exposes metadata for the document', () => {
    expect(metadata.title).toBe('Create Next App');
    expect(metadata.description).toBe('Generated by create next app');
  });

  it('builds an html tree with body styling', () => {
    const element = RootLayout({ children: <div>Hello</div> });

    expect(isValidElement(element)).toBe(true);
    if (!isValidElement(element)) return;
    expect(element.type).toBe('html');

    const body = element.props.children;
    expect(isValidElement(body)).toBe(true);
    if (!isValidElement(body)) return;
    expect(body.type).toBe('body');
    expect(body.props.className).toEqual(expect.stringContaining('font-sans'));
    expect(body.props.className).toEqual(expect.stringContaining('font-mono'));
    expect(body.props.className).toEqual(expect.stringContaining('antialiased'));
  });

  it('loads both Geist fonts from Advantage Games inputs', () => {
    const localFont = jest.requireMock('next/font/local').default as jest.Mock;

    expect(localFont).toHaveBeenNthCalledWith(1, expect.objectContaining({
      src: '../fonts/GeistVF.woff',
      variable: '--font-geist-sans',
      weight: '100 900',
    }));
    expect(localFont).toHaveBeenNthCalledWith(2, expect.objectContaining({
      src: '../fonts/GeistMonoVF.woff',
      variable: '--font-geist-mono',
      weight: '100 900',
    }));
  });
});
