/** @jest-environment node */
import { NextRequest } from "next/server";

const enabled = jest.fn(); const session = jest.fn(); const tenantDb = jest.fn(); const deps = jest.fn(); const issue = jest.fn(); const attest = jest.fn(); const complete = jest.fn();
jest.mock("@/lib/dragon-rider-host-proof-config", () => ({ isDragonRiderHostProofEnabled: () => enabled() }));
jest.mock("@/lib/session", () => ({ getCurrentUser: () => session() }));
jest.mock("@reading-advantage/db", () => ({ db: {} }));
jest.mock("@reading-advantage/domain", () => ({ createTenantDB: (...args: unknown[]) => tenantDb(...args) }));
jest.mock("@reading-advantage/domain/games", () => ({ createDragonRiderHostProofAttemptDependencies: (...args: unknown[]) => deps(...args), issueDragonRiderHostProofAttempt: (...args: unknown[]) => issue(...args), attestDragonRiderHostProofAction: (...args: unknown[]) => attest(...args), completeDragonRiderHostProofAttempt: (...args: unknown[]) => complete(...args) }));
import { POST as issuePOST } from "@/app/api/host-proof/dragon-rider/attempts/route";
import { POST as actionPOST } from "@/app/api/host-proof/dragon-rider/attempts/actions/route";
import { POST as completionPOST } from "@/app/api/host-proof/dragon-rider/completions/route";

const user = { id: "u", username: "u", display_name: "U", role: "STUDENT", school_id: "s", xp: 0, level: 1, cefr_level: "A1" };
const id = "11111111-1111-4111-8111-111111111111";
/** Creates a JSON POST request for an isolated Dragon Rider endpoint. */
function request(body: unknown) { return new NextRequest("http://localhost/api/host-proof/dragon-rider", { method: "POST", body: JSON.stringify(body) }); }
describe("Reading Dragon Rider host-proof routes", () => {
  beforeEach(() => { jest.clearAllMocks(); enabled.mockReturnValue(true); session.mockResolvedValue(user); tenantDb.mockReturnValue({}); deps.mockReturnValue({}); process.env.HOST_PROOF_ATTEMPT_SECRET = "a".repeat(32); });
  it("fails closed for disabled, unauthenticated, and tenantless requests", async () => { enabled.mockReturnValue(false); expect((await issuePOST(request({}))).status).toBe(404); enabled.mockReturnValue(true); session.mockResolvedValueOnce(null); expect((await issuePOST(request({ gameType: "dragon-rider", difficulty: "easy" }))).status).toBe(401); session.mockResolvedValueOnce({ ...user, school_id: null }); expect((await issuePOST(request({ gameType: "dragon-rider", difficulty: "easy" }))).status).toBe(403); });
  it("denies client server fields and former terminal actions before the title-local adapters run", async () => { expect((await issuePOST(request({ gameType: "dragon-rider", difficulty: "easy", xp: 99 }))).status).toBe(400); expect((await actionPOST(request({ attemptId: id, credential: "x", action: { sequence: 1, kind: "choose-gate", round: 1, gate: "left" }, serverElapsedMs: 1, input: [], seed: "x", score: 1, victory: true }))).status).toBe(400); expect((await actionPOST(request({ attemptId: id, credential: "x", action: { sequence: 1, kind: "enter-boss" } }))).status).toBe(400); expect((await actionPOST(request({ attemptId: id, credential: "x", action: { sequence: 1, kind: "defeat-boss" } }))).status).toBe(400); expect((await completionPOST(request({ attemptId: id, credential: "x", checkpoints: [], xp: 1, victory: true }))).status).toBe(400); expect(attest).not.toHaveBeenCalled(); expect(complete).not.toHaveBeenCalled(); });
  it("calls only Dragon Rider adapters with the server-derived actor and maps expected versus unexpected errors", async () => { issue.mockResolvedValue({ attemptId: id }); expect((await issuePOST(request({ gameType: "dragon-rider", difficulty: "easy" }))).status).toBe(201); expect(issue).toHaveBeenCalledWith({ userId: "u", schoolId: "s" }, { gameType: "dragon-rider", difficulty: "easy" }, {}); attest.mockRejectedValue(new Error("tampered credential checkpoint")); expect((await actionPOST(request({ attemptId: id, credential: "x", action: { sequence: 1, kind: "choose-gate", round: 1, gate: "left" } }))).status).toBe(400); complete.mockRejectedValueOnce(new Error("Dragon Rider server terminal time has not reached the admitted run duration")); const terminalResponse = await completionPOST(request({ attemptId: id, credential: "x" })); expect(terminalResponse.status).toBe(400); await expect(terminalResponse.json()).resolves.toEqual({ error: { code: "DRAGON_RIDER_ATTEMPT_REJECTED", message: "Signed attempt evidence was rejected" } }); complete.mockRejectedValueOnce(new Error("database down")); expect((await completionPOST(request({ attemptId: id, credential: "x" }))).status).toBe(500); });
});
