// Generated by scripts/build-site-assets.py. Do not edit by hand.
// Image optimization is off, so each image has an 800 and a 1600 pixel file.
// `tags` list the pages that may use the image. Chibi Quest art is primary and tutor only.

export type SiteImage = {
  sm: string;
  lg: string;
  width: number;
  height: number;
  tags: readonly ("any" | "mastery" | "primary" | "reading" | "blended" | "tutor")[];
};

export const siteImages = {
  masteryStates: { sm: "/media/images/mastery/mastery-states-800.webp", lg: "/media/images/mastery/mastery-states-1600.webp", width: 1280, height: 720, tags: ["mastery"] },
  masteryClusterHero: { sm: "/media/images/mastery/mastery-cluster-hero-800.webp", lg: "/media/images/mastery/mastery-cluster-hero-1600.webp", width: 1280, height: 720, tags: ["mastery"] },
  masteryClusterEdges: { sm: "/media/images/mastery/mastery-cluster-edges-800.webp", lg: "/media/images/mastery/mastery-cluster-edges-1600.webp", width: 1280, height: 720, tags: ["mastery"] },
  masteryPulse: { sm: "/media/images/mastery/mastery-pulse-800.webp", lg: "/media/images/mastery/mastery-pulse-1600.webp", width: 1280, height: 720, tags: ["mastery"] },
  masteryGrid: { sm: "/media/images/mastery/mastery-grid-800.webp", lg: "/media/images/mastery/mastery-grid-1600.webp", width: 1280, height: 720, tags: ["mastery"] },
  masteryPixels: { sm: "/media/images/mastery/mastery-pixels-800.webp", lg: "/media/images/mastery/mastery-pixels-1600.webp", width: 1280, height: 720, tags: ["mastery"] },
  primaryBook: { sm: "/media/images/primary/primary-book-800.webp", lg: "/media/images/primary/primary-book-1600.webp", width: 1280, height: 720, tags: ["primary", "tutor"] },
  primaryIcons: { sm: "/media/images/primary/primary-icons-800.webp", lg: "/media/images/primary/primary-icons-1600.webp", width: 1280, height: 720, tags: ["primary", "tutor"] },
  primaryBookWarm: { sm: "/media/images/primary/primary-book-warm-800.webp", lg: "/media/images/primary/primary-book-warm-1600.webp", width: 1280, height: 720, tags: ["primary", "tutor"] },
  primaryIconsWarm: { sm: "/media/images/primary/primary-icons-warm-800.webp", lg: "/media/images/primary/primary-icons-warm-1600.webp", width: 1280, height: 720, tags: ["primary", "tutor"] },
  readingWorkbookTablet: { sm: "/media/images/reading/reading-workbook-tablet-800.webp", lg: "/media/images/reading/reading-workbook-tablet-1600.webp", width: 1280, height: 720, tags: ["reading", "blended"] },
  readingBookTablet: { sm: "/media/images/reading/reading-book-tablet-800.webp", lg: "/media/images/reading/reading-book-tablet-1600.webp", width: 1280, height: 720, tags: ["reading", "blended"] },
  workbookTabletCutaway: { sm: "/media/images/blended/workbook-tablet-cutaway-800.webp", lg: "/media/images/blended/workbook-tablet-cutaway-1600.webp", width: 1280, height: 720, tags: ["blended", "reading", "mastery"] },
  blendedBookTablet: { sm: "/media/images/blended/blended-book-tablet-800.webp", lg: "/media/images/blended/blended-book-tablet-1600.webp", width: 1280, height: 720, tags: ["blended"] },
  blendedBookGlow: { sm: "/media/images/blended/blended-book-glow-800.webp", lg: "/media/images/blended/blended-book-glow-1600.webp", width: 1280, height: 720, tags: ["blended"] },
  blendedRibbon: { sm: "/media/images/blended/blended-ribbon-800.webp", lg: "/media/images/blended/blended-ribbon-1600.webp", width: 1280, height: 720, tags: ["blended"] },
  tutorQuestion: { sm: "/media/images/tutor/tutor-question-800.webp", lg: "/media/images/tutor/tutor-question-1600.webp", width: 1280, height: 720, tags: ["tutor"] },
  textureWarm: { sm: "/media/images/texture/texture-warm-800.webp", lg: "/media/images/texture/texture-warm-1600.webp", width: 1280, height: 720, tags: ["any"] },
  chibiHamletMap: { sm: "/media/images/chibi/chibi-hamlet-map-800.webp", lg: "/media/images/chibi/chibi-hamlet-map-1600.webp", width: 1536, height: 1024, tags: ["primary", "tutor"] },
  chibiHamletPoster: { sm: "/media/images/chibi/chibi-hamlet-poster-800.webp", lg: "/media/images/chibi/chibi-hamlet-poster-1600.webp", width: 1280, height: 1920, tags: ["primary", "tutor"] },
  chibiForestPoster: { sm: "/media/images/chibi/chibi-forest-poster-800.webp", lg: "/media/images/chibi/chibi-forest-poster-1600.webp", width: 1280, height: 1920, tags: ["primary", "tutor"] },
  chibiVaultPoster: { sm: "/media/images/chibi/chibi-vault-poster-800.webp", lg: "/media/images/chibi/chibi-vault-poster-1600.webp", width: 1184, height: 2096, tags: ["primary", "tutor"] },
  chibiOakClearing: { sm: "/media/images/chibi/chibi-oak-clearing-800.webp", lg: "/media/images/chibi/chibi-oak-clearing-1600.webp", width: 1500, height: 950, tags: ["primary", "tutor"] },
  screenArticleReading: { sm: "/media/images/screens/screen-article-reading-800.webp", lg: "/media/images/screens/screen-article-reading-1600.webp", width: 1600, height: 1000, tags: ["reading"] },
  screenGamesLibrary: { sm: "/media/images/screens/screen-games-library-800.webp", lg: "/media/images/screens/screen-games-library-1600.webp", width: 1600, height: 1000, tags: ["reading"] },
  screenMagicDefense: { sm: "/media/images/screens/screen-magic-defense-800.webp", lg: "/media/images/screens/screen-magic-defense-1600.webp", width: 1600, height: 939, tags: ["reading"] },
  screenStudentReports: { sm: "/media/images/screens/screen-student-reports-800.webp", lg: "/media/images/screens/screen-student-reports-1600.webp", width: 1600, height: 1000, tags: ["reading", "blended"] },
} as const satisfies Record<string, SiteImage>;

export const siteLogos = {
  codecamp: { color: "/media/brand/logos/svg/codecamp-advantage.svg", reversed: "/media/brand/logos/reversed/codecamp-advantage-reversed.svg", thaiLockup: "/media/brand/logos/lockups/codecamp-advantage-thai-lockup.svg" },
  mastery: { color: "/media/brand/logos/svg/mastery-advantage.svg", reversed: "/media/brand/logos/reversed/mastery-advantage-reversed.svg", thaiLockup: "/media/brand/logos/lockups/mastery-advantage-thai-lockup.svg" },
  math: { color: "/media/brand/logos/svg/math-advantage.svg", reversed: "/media/brand/logos/reversed/math-advantage-reversed.svg", thaiLockup: "/media/brand/logos/lockups/math-advantage-thai-lockup.svg" },
  primary: { color: "/media/brand/logos/svg/primary-advantage.svg", reversed: "/media/brand/logos/reversed/primary-advantage-reversed.svg", thaiLockup: "/media/brand/logos/lockups/primary-advantage-thai-lockup.svg" },
  reading: { color: "/media/brand/logos/svg/reading-advantage.svg", reversed: "/media/brand/logos/reversed/reading-advantage-reversed.svg", thaiLockup: "/media/brand/logos/lockups/reading-advantage-thai-lockup.svg" },
  science: { color: "/media/brand/logos/svg/science-advantage.svg", reversed: "/media/brand/logos/reversed/science-advantage-reversed.svg", thaiLockup: "/media/brand/logos/lockups/science-advantage-thai-lockup.svg" },
  stem: { color: "/media/brand/logos/svg/stem-advantage.svg", reversed: "/media/brand/logos/reversed/stem-advantage-reversed.svg", thaiLockup: "/media/brand/logos/lockups/stem-advantage-thai-lockup.svg" },
  storytime: { color: "/media/brand/logos/svg/storytime-advantage.svg", reversed: "/media/brand/logos/reversed/storytime-advantage-reversed.svg", thaiLockup: "/media/brand/logos/lockups/storytime-advantage-thai-lockup.svg" },
  tutor: { color: "/media/brand/logos/svg/tutor-advantage.svg", reversed: "/media/brand/logos/reversed/tutor-advantage-reversed.svg", thaiLockup: "/media/brand/logos/lockups/tutor-advantage-thai-lockup.svg" },
  zhongwen: { color: "/media/brand/logos/svg/zhongwen-advantage.svg", reversed: "/media/brand/logos/reversed/zhongwen-advantage-reversed.svg", thaiLockup: "/media/brand/logos/lockups/zhongwen-advantage-thai-lockup.svg" },
} as const;

export const siteVideos = {
  masteryBloom: { src: "/media/video/mastery-graph-bloom.mp4", poster: "/media/video/mastery-graph-bloom-poster.webp" },
} as const;
