/** Generated by scripts/apk2d-pack.ts: the 2D camera of the baked background (backgrounds/devourer-slime.png). */
import type { Projection2D } from '@reading-advantage/advantage-play-kit-3d/view2d/projection';

export const BACKGROUND_FILE = 'background.devourer-slime';
export const PROJECTION: Projection2D = {"elevation":45,"ppm":64,"uMin":-9.5,"vMax":10.36645579206333,"width":1216,"height":1093};
