import { randomUUID } from "node:crypto";

import type { ZodIssue } from "zod";

import type { FinanceOperationScope } from "../finance-operations/contracts.js";
import {
  accountingSubmissionInputSchema,
  accountingSubmissionSchema,
  type AccountingSubmission,
  type AccountingSubmissionInput,
} from "./contracts.js";

/**
 * SSO-authorized Accounting caller. The actor alone carries the company scope:
 * the domain derives the persistence scope from `companyId` and never accepts a
 * caller-supplied scope.
 */
export interface AccountingActor {
  /** Account identity (uuid) of the caller. */
  readonly accountId: string;
  /** Company the caller acts within; becomes the persistence scope. */
  readonly companyId: string;
  /** Company role of the caller; must be STAFF, OWNER, or ACCOUNTANT. */
  readonly role: string;
}

/** Actor-scoped identity used to look up a submission by idempotency key. */
export interface AccountingSubmissionIdempotencyIdentity {
  /** Actor-derived company boundary for the lookup. */
  readonly scope: Readonly<FinanceOperationScope>;
  /** Submitting account; idempotency keys are scoped per actor. */
  readonly submittedByAccountId: string;
  /** Stable request identity supplied by the caller. */
  readonly idempotencyKey: string;
}

/** Persistence boundary for company-scoped accounting submissions. */
export interface AccountingSubmissionRepository {
  /**
   * Persists a pending submission.
   * @param submission Immutable submission snapshot generated by the domain.
   * @param idempotencyKey Caller request identity to store for replay, when given.
   * @returns The stored submission snapshot.
   */
  insert(
    submission: AccountingSubmission,
    idempotencyKey?: string,
  ): Promise<AccountingSubmission>;

  /**
   * Finds a previously stored submission for one actor and idempotency key.
   * @param identity Actor-derived scope, submitter, and idempotency key.
   * @returns The original submission, or undefined when the key is unused.
   */
  findByIdempotencyKey(
    identity: AccountingSubmissionIdempotencyIdentity,
  ): Promise<AccountingSubmission | undefined>;

  /**
   * Lists every submission inside one company scope.
   * @param scope Actor-derived company boundary for the listing.
   * @returns The submissions stored under the scope.
   */
  listByScope(
    scope: Readonly<FinanceOperationScope>,
  ): Promise<readonly AccountingSubmission[]>;
}

/** Stable reason an accounting submission operation was rejected. */
export type AccountingSubmissionErrorReason = "invalid-input" | "forbidden";

/** Structured failure from an accounting submission operation. */
export class AccountingSubmissionError extends Error {
  /** Stable machine-readable rejection reason. */
  readonly reason: AccountingSubmissionErrorReason;

  /** Zod issues describing the rejected input; present only for "invalid-input". */
  readonly issues?: readonly ZodIssue[];

  /**
   * Creates a structured accounting submission error.
   * @param reason Stable rejection reason for callers and tests.
   * @param issues Zod issues carried when the reason is "invalid-input".
   */
  constructor(
    reason: AccountingSubmissionErrorReason,
    issues?: readonly ZodIssue[],
  ) {
    super(reason);
    this.name = "AccountingSubmissionError";
    this.reason = reason;
    this.issues = issues;
  }
}

const ACCOUNTING_ROLES: ReadonlySet<string> = new Set([
  "STAFF",
  "OWNER",
  "ACCOUNTANT",
]);

function requireAccountingRole(actor: AccountingActor): void {
  if (!ACCOUNTING_ROLES.has(actor.role)) {
    throw new AccountingSubmissionError("forbidden");
  }
}

function actorScope(actor: AccountingActor): Readonly<FinanceOperationScope> {
  return { companyId: actor.companyId };
}

/**
 * Validates, authorizes, and persists one expense or bill submission under the
 * actor's company scope. A replay with the same actor and idempotency key
 * returns the original submission without a second insert.
 * @param request Repository port, actor, submission input, and optional idempotency key.
 * @returns The stored pending submission, or the original on an idempotent replay.
 * @throws AccountingSubmissionError when the actor lacks an accounting role or the input is invalid.
 */
export async function submitAccountingSubmission(request: {
  readonly repository: AccountingSubmissionRepository;
  readonly actor: AccountingActor;
  readonly input: AccountingSubmissionInput;
  readonly idempotencyKey?: string;
}): Promise<AccountingSubmission> {
  requireAccountingRole(request.actor);

  const parsed = accountingSubmissionInputSchema.safeParse(request.input);
  if (!parsed.success) {
    throw new AccountingSubmissionError("invalid-input", parsed.error.issues);
  }

  const scope = actorScope(request.actor);
  if (request.idempotencyKey !== undefined) {
    const existing = await request.repository.findByIdempotencyKey({
      scope,
      submittedByAccountId: request.actor.accountId,
      idempotencyKey: request.idempotencyKey,
    });
    if (existing !== undefined) {
      return existing;
    }
  }

  const submission = accountingSubmissionSchema.parse({
    id: randomUUID(),
    scope,
    status: "pending",
    submittedByAccountId: request.actor.accountId,
    submittedAt: new Date().toISOString(),
    ...parsed.data,
  });
  return request.repository.insert(submission, request.idempotencyKey);
}

/**
 * Lists submissions inside the actor's company scope. STAFF actors receive only
 * their own submissions; OWNER and ACCOUNTANT actors receive every submission
 * in the scope.
 * @param request Repository port and actor.
 * @returns The submissions visible to the actor.
 * @throws AccountingSubmissionError when the actor lacks an accounting role.
 */
export async function listAccountingSubmissions(request: {
  readonly repository: AccountingSubmissionRepository;
  readonly actor: AccountingActor;
}): Promise<readonly AccountingSubmission[]> {
  requireAccountingRole(request.actor);

  const submissions = await request.repository.listByScope(
    actorScope(request.actor),
  );
  if (request.actor.role === "STAFF") {
    return submissions.filter(
      (submission) =>
        submission.submittedByAccountId === request.actor.accountId,
    );
  }
  return submissions;
}
