import { randomUUID } from "node:crypto";

import { z } from "zod";
import type { ZodIssue } from "zod";

import type { FinanceOperationScope } from "../finance-operations/contracts.js";
import {
  accountingSubmissionAuditEventSchema,
  accountingSubmissionIdempotencyKeySchema,
  accountingSubmissionInputSchema,
  accountingSubmissionResultSchema,
  accountingSubmissionSchema,
  rejectReasonSchema,
  type AccountingSubmission,
  type AccountingSubmissionAuditEvent,
  type AccountingSubmissionInput,
  type AccountingSubmissionResult,
} from "./contracts.js";

/**
 * SSO-authorized Accounting caller. The actor alone carries the company scope:
 * the domain derives the persistence scope from `companyId` and never accepts a
 * caller-supplied scope.
 */
export interface AccountingActor {
  /** Account identity (uuid) of the caller. */
  readonly accountId: string;
  /** Company the caller acts within; becomes the persistence scope. */
  readonly companyId: string;
  /** Company role of the caller; must be STAFF, OWNER, or ACCOUNTANT. */
  readonly role: string;
}

/** Actor-scoped identity used to look up a submission by idempotency key. */
export interface AccountingSubmissionIdempotencyIdentity {
  /** Actor-derived company boundary for the lookup. */
  readonly scope: Readonly<FinanceOperationScope>;
  /** Submitting account; idempotency keys are scoped per actor. */
  readonly submittedByAccountId: string;
  /** Stable request identity supplied by the caller. */
  readonly idempotencyKey: string;
}

/** Persistence boundary for company-scoped accounting submissions. */
export interface AccountingSubmissionRepository {
  /**
   * Persists a pending submission and its submit audit event in one transaction.
   * @param submission Immutable submission snapshot generated by the domain.
   * @param idempotencyKey Caller request identity to store for replay, when given.
   * @param auditEvent Append-only submit audit event for the submission.
   * @returns The stored submission snapshot.
   */
  insert(
    submission: AccountingSubmission,
    idempotencyKey: string | undefined,
    auditEvent: AccountingSubmissionAuditEvent,
  ): Promise<AccountingSubmission>;

  /**
   * Finds a previously stored submission for one actor and idempotency key.
   * @param identity Actor-derived scope, submitter, and idempotency key.
   * @returns The original submission, or undefined when the key is unused.
   */
  findByIdempotencyKey(
    identity: AccountingSubmissionIdempotencyIdentity,
  ): Promise<AccountingSubmission | undefined>;

  /**
   * Lists every submission inside one company scope.
   * @param scope Actor-derived company boundary for the listing.
   * @returns The submissions stored under the scope.
   */
  listByScope(
    scope: Readonly<FinanceOperationScope>,
  ): Promise<readonly AccountingSubmission[]>;

  /**
   * Finds a submission by id inside one company scope.
   * @param input Actor-derived scope and submission identifier.
   * @returns The submission, or undefined when unknown.
   */
  findById(input: {
    readonly scope: Readonly<FinanceOperationScope>;
    readonly submissionId: string;
  }): Promise<AccountingSubmission | undefined>;

  /**
   * Transitions a pending submission to approved or rejected and records the audit event.
   * @param input Scope, submission id, target status, and audit event.
   * @returns The updated submission, or undefined when unknown or not pending.
   */
  transition(input: {
    readonly scope: Readonly<FinanceOperationScope>;
    readonly submissionId: string;
    readonly status: "approved" | "rejected";
    readonly auditEvent: AccountingSubmissionAuditEvent;
  }): Promise<AccountingSubmission | undefined>;
}

/** Stable reason an accounting submission operation was rejected. */
export type AccountingSubmissionErrorReason =
  | "invalid-input"
  | "forbidden"
  | "not-found"
  | "conflict";

/** Structured failure from an accounting submission operation. */
export class AccountingSubmissionError extends Error {
  /** Stable machine-readable rejection reason. */
  readonly reason: AccountingSubmissionErrorReason;

  /** Zod issues describing the rejected input; present only for "invalid-input". */
  readonly issues?: readonly ZodIssue[];

  /**
   * Creates a structured accounting submission error.
   * @param reason Stable rejection reason for callers and tests.
   * @param issues Zod issues carried when the reason is "invalid-input".
   */
  constructor(
    reason: AccountingSubmissionErrorReason,
    issues?: readonly ZodIssue[],
  ) {
    super(reason);
    this.name = "AccountingSubmissionError";
    this.reason = reason;
    this.issues = issues;
  }
}

const ACCOUNTING_ROLES: ReadonlySet<string> = new Set([
  "STAFF",
  "OWNER",
  "ACCOUNTANT",
]);
const PRIVATE_EVIDENCE_REFERENCE_PREFIX = "private-evidence://";

type CompareAccountingSubmissionEvidence = (input: {
  readonly candidateEvidenceReference: string;
  readonly storedEvidenceReference: string;
}) => Promise<boolean>;

function requireAccountingRole(actor: AccountingActor): void {
  if (!ACCOUNTING_ROLES.has(actor.role)) {
    throw new AccountingSubmissionError("forbidden");
  }
}

function actorScope(actor: AccountingActor): Readonly<FinanceOperationScope> {
  return { companyId: actor.companyId };
}

/** Checks whether a validated evidence reference belongs to the actor's company. */
function evidenceBelongsToCompany(
  evidenceReference: string,
  companyId: string,
): boolean {
  return evidenceReference.startsWith(
    `${PRIVATE_EVIDENCE_REFERENCE_PREFIX}${companyId}/`,
  );
}

/**
 * Compares the request content that an idempotency key represents.
 * @param input Validated submission input.
 * @param stored Previously stored submission.
 * @returns True when all request fields match, excluding the generated evidence reference.
 */
function hasSameSubmissionContent(
  input: AccountingSubmissionInput,
  stored: AccountingSubmission,
  compareEvidence?: CompareAccountingSubmissionEvidence,
): Promise<boolean> {
  const hasSameScalarContent =
    input.kind === stored.kind &&
    input.payee === stored.payee &&
    input.category === stored.category &&
    input.description === stored.description &&
    input.money.amountMinor === stored.money.amountMinor &&
    input.money.currency === stored.money.currency &&
    input.settledThbAmount === stored.settledThbAmount;
  if (!hasSameScalarContent) return Promise.resolve(false);
  if (input.evidenceReference === stored.evidenceReference) {
    return Promise.resolve(true);
  }
  if (compareEvidence === undefined) return Promise.resolve(false);
  return compareEvidence({
    candidateEvidenceReference: input.evidenceReference,
    storedEvidenceReference: stored.evidenceReference,
  });
}

/**
 * Validates, authorizes, and persists one expense or bill submission under the
 * actor's company scope, with a typed created or replayed result.
 * @param request Repository port, actor, submission input, and optional idempotency key.
 * @returns The stored submission and whether this request created or replayed it.
 * @throws AccountingSubmissionError when the actor lacks an accounting role or the input is invalid.
 */
export async function submitAccountingSubmissionWithOutcome(request: {
  readonly repository: AccountingSubmissionRepository;
  readonly actor: AccountingActor;
  readonly input: AccountingSubmissionInput;
  readonly idempotencyKey?: string;
  readonly compareEvidence?: CompareAccountingSubmissionEvidence;
}): Promise<AccountingSubmissionResult> {
  requireAccountingRole(request.actor);

  const parsed = accountingSubmissionInputSchema.safeParse(request.input);
  if (!parsed.success) {
    throw new AccountingSubmissionError("invalid-input", parsed.error.issues);
  }

  if (
    !evidenceBelongsToCompany(
      parsed.data.evidenceReference,
      request.actor.companyId,
    )
  ) {
    throw new AccountingSubmissionError("forbidden");
  }

  let idempotencyKey: string | undefined;
  if (request.idempotencyKey !== undefined) {
    const parsedIdempotencyKey =
      accountingSubmissionIdempotencyKeySchema.safeParse(
        request.idempotencyKey,
      );
    if (!parsedIdempotencyKey.success) {
      throw new AccountingSubmissionError(
        "invalid-input",
        parsedIdempotencyKey.error.issues,
      );
    }
    idempotencyKey = parsedIdempotencyKey.data;
  }

  const scope = actorScope(request.actor);
  if (idempotencyKey !== undefined) {
    const existing = await request.repository.findByIdempotencyKey({
      scope,
      submittedByAccountId: request.actor.accountId,
      idempotencyKey,
    });
    if (existing !== undefined) {
      if (
        !(await hasSameSubmissionContent(
          parsed.data,
          existing,
          request.compareEvidence,
        ))
      ) {
        throw new AccountingSubmissionError("conflict");
      }
      return accountingSubmissionResultSchema.parse({
        submission: existing,
        outcome: "replayed",
      });
    }
  }

  const submission = accountingSubmissionSchema.parse({
    id: randomUUID(),
    scope,
    status: "pending",
    submittedByAccountId: request.actor.accountId,
    submittedAt: new Date().toISOString(),
    ...parsed.data,
  });
  const auditEvent = accountingSubmissionAuditEventSchema.parse({
    id: randomUUID(),
    submissionId: submission.id,
    action: "submit",
    actorAccountId: request.actor.accountId,
    actorRole: request.actor.role,
    createdAt: new Date().toISOString(),
  });
  const stored = await request.repository.insert(
    submission,
    idempotencyKey,
    auditEvent,
  );
  if (
    idempotencyKey !== undefined &&
    !(await hasSameSubmissionContent(
      parsed.data,
      stored,
      request.compareEvidence,
    ))
  ) {
    throw new AccountingSubmissionError("conflict");
  }
  return accountingSubmissionResultSchema.parse({
    submission: stored,
    outcome: stored.id === submission.id ? "created" : "replayed",
  });
}

/**
 * Validates, authorizes, and persists one expense or bill submission.
 * @param request Repository port, actor, submission input, and optional idempotency key.
 * @returns The stored pending submission, or the original on an idempotent replay.
 * @throws AccountingSubmissionError when the actor lacks an accounting role or the input is invalid.
 */
export async function submitAccountingSubmission(request: {
  readonly repository: AccountingSubmissionRepository;
  readonly actor: AccountingActor;
  readonly input: AccountingSubmissionInput;
  readonly idempotencyKey?: string;
  readonly compareEvidence?: CompareAccountingSubmissionEvidence;
}): Promise<AccountingSubmission> {
  const result = await submitAccountingSubmissionWithOutcome(request);
  return result.submission;
}

/**
 * Lists submissions inside the actor's company scope. STAFF actors receive only
 * their own submissions; OWNER and ACCOUNTANT actors receive every submission
 * in the scope.
 * @param request Repository port and actor.
 * @returns The submissions visible to the actor.
 * @throws AccountingSubmissionError when the actor lacks an accounting role.
 */
export async function listAccountingSubmissions(request: {
  readonly repository: AccountingSubmissionRepository;
  readonly actor: AccountingActor;
}): Promise<readonly AccountingSubmission[]> {
  requireAccountingRole(request.actor);

  const submissions = await request.repository.listByScope(
    actorScope(request.actor),
  );
  if (request.actor.role === "STAFF") {
    return submissions.filter(
      (submission) =>
        submission.submittedByAccountId === request.actor.accountId,
    );
  }
  return submissions;
}

const submissionIdSchema = z.string().uuid();

function requireOwnerRole(actor: AccountingActor): void {
  if (actor.role !== "OWNER") {
    throw new AccountingSubmissionError("forbidden");
  }
}

/**
 * Approves a pending submission. Only OWNER actors may approve.
 * @param request Repository port, actor, and submission identifier.
 * @returns The approved submission.
 * @throws AccountingSubmissionError when the actor is not OWNER, the id is invalid, or the submission is unknown or not pending.
 */
export async function approveAccountingSubmission(request: {
  readonly repository: AccountingSubmissionRepository;
  readonly actor: AccountingActor;
  readonly submissionId: string;
}): Promise<AccountingSubmission> {
  requireOwnerRole(request.actor);

  const parsedId = submissionIdSchema.safeParse(request.submissionId);
  if (!parsedId.success) {
    throw new AccountingSubmissionError("invalid-input", parsedId.error.issues);
  }

  const auditEvent = accountingSubmissionAuditEventSchema.parse({
    id: randomUUID(),
    submissionId: parsedId.data,
    action: "approve",
    actorAccountId: request.actor.accountId,
    actorRole: request.actor.role,
    createdAt: new Date().toISOString(),
  });

  const result = await request.repository.transition({
    scope: actorScope(request.actor),
    submissionId: parsedId.data,
    status: "approved",
    auditEvent,
  });

  if (result === undefined) {
    throw new AccountingSubmissionError("not-found");
  }
  return result;
}

/**
 * Rejects a pending submission with a reason. Only OWNER actors may reject.
 * @param request Repository port, actor, submission identifier, and rejection reason.
 * @returns The rejected submission.
 * @throws AccountingSubmissionError when the actor is not OWNER, the id or reason is invalid, or the submission is unknown or not pending.
 */
export async function rejectAccountingSubmission(request: {
  readonly repository: AccountingSubmissionRepository;
  readonly actor: AccountingActor;
  readonly submissionId: string;
  readonly reason: string | undefined;
}): Promise<AccountingSubmission> {
  requireOwnerRole(request.actor);

  const parsedId = submissionIdSchema.safeParse(request.submissionId);
  if (!parsedId.success) {
    throw new AccountingSubmissionError("invalid-input", parsedId.error.issues);
  }

  const parsedReason = rejectReasonSchema.safeParse(request.reason);
  if (!parsedReason.success) {
    throw new AccountingSubmissionError(
      "invalid-input",
      parsedReason.error.issues,
    );
  }

  const auditEvent = accountingSubmissionAuditEventSchema.parse({
    id: randomUUID(),
    submissionId: parsedId.data,
    action: "reject",
    actorAccountId: request.actor.accountId,
    actorRole: request.actor.role,
    reason: parsedReason.data,
    createdAt: new Date().toISOString(),
  });

  const result = await request.repository.transition({
    scope: actorScope(request.actor),
    submissionId: parsedId.data,
    status: "rejected",
    auditEvent,
  });

  if (result === undefined) {
    throw new AccountingSubmissionError("not-found");
  }
  return result;
}
