#!/usr/bin/env bash
# Generates deterministic Measure architecture facts for this monorepo.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"
mkdir -p measure/generated

node --input-type=module <<'NODE'
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { execFileSync } from "node:child_process";

const roots = ["apps", "packages", "services"].filter((path) => {
  try { return statSync(path).isDirectory(); } catch { return false; }
});
const sourceRevision = execFileSync("git", ["rev-parse", "HEAD"], { encoding: "utf8" }).trim();
const generatedAt = execFileSync("git", ["show", "-s", "--format=%cI", "HEAD"], { encoding: "utf8" }).trim();

function directories(path) {
  return readdirSync(path, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && !entry.name.startsWith("."))
    .map((entry) => entry.name)
    .sort();
}

function walk(path, accept, output = []) {
  for (const entry of readdirSync(path, { withFileTypes: true })) {
    if (["node_modules", ".next", ".turbo", "dist", "coverage"].includes(entry.name)) continue;
    const absolute = join(path, entry.name);
    if (entry.isDirectory()) walk(absolute, accept, output);
    else if (accept(absolute)) output.push(absolute);
  }
  return output;
}

const workspaces = Object.fromEntries(roots.map((root) => [root, directories(root)]));
const routes = roots.includes("apps")
  ? walk("apps", (path) => /\/app\/.*\/(page|layout|route)\.(ts|tsx)$/.test(path))
      .map((path) => relative(".", path).replaceAll("\\", "/"))
      .sort()
  : [];
const architecture = {
  schemaVersion: "measure.architecture.v1",
  generatedAt,
  sourceRevision,
  projectType: "typescript-monorepo",
  workspaceRoots: workspaces,
  routeCount: routes.length,
};

writeFileSync("measure/generated/architecture.json", `${JSON.stringify(architecture, null, 2)}\n`);
writeFileSync("measure/generated/routes.md", [
  "# Application Routes (generated)",
  "",
  `Source revision: \`${sourceRevision}\``,
  "",
  "> Generated by `measure/generate.sh`; do not edit manually.",
  "",
  ...routes.map((route) => `- \`${route}\``),
  "",
].join("\n"));
NODE

echo "Generated measure/generated/architecture.json and measure/generated/routes.md"
